### ISSUE TITLE
Duo Pam auth failure

### ISSUE THREAD

**Issue by mxcheng2011** [unlhcc/jupyter-duoauthenticator#1]
We are testing this and got some problem. The jupyterhub doesn't give any webpage for DUO prompts. 

the pam prints error like 
python: Aborted Duo login for 'xxx': Error gathering user response

Do you know how to troubleshoot? Thank you!

Mengxing

**Comment by mxcheng2011** [comment]
It works. Thank you! The document could be enhanced a bit. The jupyterhub_config.py must include the `import duoauthenticator`.

**Comment by acaprez** [comment]
Hello,

I wasn't able to look at this until now, so I'm glad you were able to get it working.  Thanks for the suggestion - I will update the docs to reflect the needed `import` statement.
